### ISSUE TITLE
keras mismatch version in installer

### ISSUE THREAD

**Issue by rsanchezgarc** [I2PC/scipion-em-xmipp#103]
https://github.com/I2PC/scipion-em-xmipp/blob/dbb6c18e9d02df3ee2dffe230205208426c061f7/xmipp3/__init__.py#L275

Keras installed in cpu version should be the same that gpu version. So this line should be changed to version 2.1.5. Otherwise, trained models my not work.

**Comment by dmaluenda** [comment]
Fixed in #111
