### ISSUE TITLE
Protocol Split Volume Hierarchical cluster is handlin threads/MPI in strange way

### ISSUE THREAD

**Issue by DStrelak** [I2PC/scipion-em-xmipp#105]
This protocol is accepting MPI arg only. 
The programs are, however,  using mostly MPI = 1 * noOfThreads (which looks strange).
Please have a look which of them can utilize more MPI and / or threads.

**Comment by albertmena** [comment]
Some runJobs uses 1 mpi others has implemented multithreds.
