### ISSUE TITLE
xmipp_classify_CL2D doesn't produce images.xmd

### ISSUE THREAD

**Issue by dallakyan** [I2PC/scipion-em-xmipp#107]
Thank you for developing xmipp. We are having an issue when xmipp_classify_CL2D doesn't produce images.xmd output file. This is sporadic and when I rerun it second time it produces images.xmd as expected. Since in our case it takes about 6 hours to finish xmipp_classify_CL2D, I was wandering if anyone else has seen this problem or knows a workaround. Thank you.

Here an example of xmipp_classify_CL2D  command:
```
mpirun -np 56 xmipp_classify_CL2D  -i 19may23a/align/cl2d4_sub1/19may28z49.hed --nref 40 --iter 15 --odir 19may23a/align/cl2d4_sub1 --oroot part19may28z49 --classifyAllImages --distance correlation --classicalMultiref
```
It finishes fine with no errors and creates level_01 to level_03 folders with all the output except sometimes it makes  images.xmd  and sometimes it doesn't.

**Comment by dmaluenda** [comment]
@dallakyan, thank you for reporting!

We have not experienced this before, at least I have not listened before.

You have experiencing this issue in different projects or it is only happening in a single project?

Are you getting this issue just from the last version update (to Scipion v3-Diocletian / Xmipp-19.03)?

Our apologies for this late reply.

**Comment by dallakyan** [comment]
Thank you @dmaluenda. We have experiencing this issue in different projects.  We are using Xmipp version: 3.18.08.

We are running Xmipp through Appion and I have found a workaround. Since we don't use  images.xmd downstream, I copy .xmd file from level_01 if it can't find images.xmd. Works great so far.
