### ISSUE TITLE
keras incorrect version

### ISSUE THREAD

**Issue by rsanchezgarc** [I2PC/scipion-em-xmipp#131]
keras is being installed as version 2.2.2. when it used to be installed as 2.1.5. 
This breaks compatibility with cuda8 and, additionally, it is causing trained models (as deep consensus ones) not being working.
So  this line in xmipp3/__init__.py should be changed (although it may cause some problems in other models, double check is required and perhaps is the moment to study virtual environments)

        keras = tryAddPipModule(env, 'keras', '2.2.2', target='keras*',

---->

   keras = tryAddPipModule(env, 'keras', '2.1.5', target='keras*',

I do not know why version 2.1.5 was changed to 2.2.2 in commit f8e64fb.
@dmaluenda  any clue?

**Comment by dmaluenda** [comment]
I remember an issue (and its PR) just in the opposite direction...

**Comment by rsanchezgarc** [comment]
If you mean the issue #103
I think that you did in the opposite direction I suggested ("So this line should be changed to version 2.1.5.")
Please double check it.

**Comment by dmaluenda** [comment]
Auch! I see.. we (I and Erney) thought that the newer version would be the best option for backwards compatibility..

**Comment by rsanchezgarc** [comment]
Eventually we will be able to rely on anaconda envs to manage that problem but now we have to make a decision. Remove cuda8 compatibility or keep the 2 versions of keras.

**Comment by DStrelak** [comment]
@rsanchezgarc what is the status?

**Comment by rsanchezgarc** [comment]
I guess it is fully solved since we moved to anaconda.
