### ISSUE TITLE
ignoring gain image by OF alignment 

### ISSUE THREAD

**Issue by mohsenkazemi** [I2PC/scipion-em-xmipp#133]
**Describe the bug**
Our movies are Tiff format with the separated gain image. MotionCorr works well with input movies and gain image and produces normal output micrographs. However, OF alignment, will produce output micrographs that looks the ones without correcting for gain! Please see attached.
*** it is not the case for .mrc files

**To Reproduce**
1. import some tif movies and gain image. 
2. use those as the input for OF, or the output of motionCorr
3. See the output micrographs of OF

**Expected behavior**
output micrographs are looked uncorrected for gain!

**Desktop (please complete the following information):**
 - OS: Ubuntu 16
 - Version [2] 

![motionCorr](https://user-images.githubusercontent.com/15126234/61846378-3f5ab400-aeea-11e9-9479-b8f90d577558.jpg)
![OF](https://user-images.githubusercontent.com/15126234/61846379-3f5ab400-aeea-11e9-9806-d3f5a6d05d3a.jpg)

**Comment by pconesa** [comment]
I'd say the gain is applied but not fliped. Can you try to flip the gain image on Y.

**Comment by mohsenkazemi** [comment]
Hi @pconesa ... I tried fliped gain and it works if you give the imported movie with fliped gain, however, in this case, motionCorr is not working well. So, I am not sure if it is possible to add a kind of option in Xmipp-OF input parameters to flip the gain image if it happens? But, the interesting point is that this issue is not the case for all dataset (at least for me)!

**Comment by pconesa** [comment]
Motioncor2 has an advanced parameter to flip the gain. 
The decision about to flip or not to flip must come from you, Scipion, Xmipp, motioncorr are passive on this.

I think, OF does not have those options to flip the gain.

**Comment by mohsenkazemi** [comment]
I Understand your point and I am aware that OF has no option for that, but it may need one. Thanks anyway.
