### ISSUE TITLE
xmipp - preprocess micrographs

### ISSUE THREAD

**Issue by JuhaHuiskonen** [I2PC/scipion-em-xmipp#146]
When restarting 'xmipp - preprocess micrographs' in continue mode it starts from beginning and does not skip the micrographs that have been done already.  I suggest to fix the continue mode to work as intended.

**Comment by danielmarchan3** [comment]
I have checked this issue and when stoping and then continuing the processing, only the new micrographs are processed as it starts from the ones that are not pointed in the DONE file.
