### ISSUE TITLE
particle boxsize estimator not working properly

### ISSUE THREAD

**Issue by rsanchezgarc** [I2PC/scipion-em-xmipp#149]
I have tried the protocol with 2 datasets  (empiar 10061 and empiar 10028)and the results are nonsense (like 72 pred vs 500 actual).

Some debugging should be performed on that or, if not possible, this protocol should be "hidden" until fixed.

I think that there is training code also in xmipp, so it could be possible to retrain it if there where problems with it, but I bet on some sampling rate related problem rather than training

**Comment by albertmena** [comment]
Protocol will be moved to deprecated: https://github.com/I2PC/scipion-em-xmipp/issues/523
