### ISSUE TITLE
ML2D viewer does not work

### ISSUE THREAD

**Issue by ldelcano** [I2PC/scipion-em-xmipp#156]
Xmipp ML2D viewer does not do anything. This is due to the fact that extra directory is empty. All intermediate result files from iterations are instead on a ml2d_extra directory. This is probably like this since October 2014 (commit id 2b6ada5)

**Comment by DStrelak** [comment]
@ldelcano  is this still relevant?

**Comment by ldelcano** [comment]
Nor sure, is ML2D still used/supported? I have no idea.

**Comment by dmaluenda** [comment]
I think not. @cossorzano?

**Comment by cossorzano** [comment]
It is not, but if it is a matter of the viewer, it can be quickly solved. @danielmarchan3

**Comment by danielmarchan3** [comment]
Viewer Fixed
