### ISSUE TITLE
Error in High-Res when GPU is activated

### ISSUE THREAD

**Issue by dmaluenda** [I2PC/scipion-em-xmipp#162]
From: https://scipion.slack.com/archives/CA77ZNCMC/p1573516719000600

I am running xmipp-highRes on a dataset using GPU, but it has an error
"Parameter incorrect". It is in 'step 6: reconstruct' and the log is as
follow. Do you have any idea if the problem is in my Scipion
configuration. I am using scipion2 and just installed on this machine
two days ago. Also, I am using cuda 8.0, and using the CPU, protocol works very well.

00304:    Direct 3D reconstruction method using Kaiser windows as interpolators
00305:    =====================================================================
00306:    Input selfile             : Runs/003545_XmippProtReconstructHighRes/extra/Iter001/images_corrected01.xmd
00307:    padding_factor_proj       : 2
00308:    padding_factor_vol        : 2
00309:    Output volume             : Runs/003545_XmippProtReconstructHighRes/extra/Iter001/volume01.vol
00310:    Symmetry file for projections : c1
00311:    Use weights stored in the image headers or doc file
00312:
00313:    Interpolation Function
00314:      blrad                 : 1.9
00315:      blord                 : 0
00316:      blalpha               : 15
00317:    max_resolution          : 0.5
00318:    -----------------------------------------------------------------
00319:   Available memory: 11015MB
00320:   Required memory (at least): 7MB
00321:   0000/???? sec. ------------------------------------------------------------XMIPP_ERROR 54:  Parameter incorrect.
00322:   Only pointer aligned to the page size can be registered
00323:   File: libraries/reconstruction_cuda/gpu.cpp line: 96
00324:   Traceback (most recent call last):
00325:     File "/home/mohsen/scipion-v2/scipion/pyworkflow/protocol/protocol.py", line 186, in run
00326:       self._run()
00327:     File "/home/mohsen/scipion-v2/scipion/pyworkflow/protocol/protocol.py", line 237, in _run
00328:       resultFiles = self._runFunc()
00329:     File "/home/mohsen/scipion-v2/scipion/pyworkflow/protocol/protocol.py", line 233, in _runFunc
00330:       return self._func(*self._args)
00331:
File
"/home/mohsen/scipion-v2/xmipp-bundle/src/scipion-em-xmipp/xmipp3/protocols/protocol_reconstruct_highres.py",
line 1270, in reconstruct
00332:       self.runJob('xmipp_cuda_reconstruct_fourier ', tmpArgs, numberOfMpi=1)
00333:     File "/home/mohsen/scipion-v2/scipion/pyworkflow/protocol/protocol.py", line 1311, in runJob
00334:       self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
00335:     File "/home/mohsen/scipion-v2/scipion/pyworkflow/protocol/executor.py", line 70, in runJob
00336:       env=env, cwd=cwd, gpuList=self.getGpuList())
00337:     File "/home/mohsen/scipion-v2/scipion/pyworkflow/utils/process.py", line 52, in runJob
00338:       return runCommand(command, env, cwd)
00339:     File "/home/mohsen/scipion-v2/scipion/pyworkflow/utils/process.py", line 67, in runCommand
00340:       env=env, cwd=cwd)
00341:     File "/home/mohsen/scipion-v2/scipion/software/lib/python2.7/subprocess.py", line 190, in check_call
00342:       raise CalledProcessError(retcode, cmd)
00343:   CalledProcessError: Command 'xmipp_cuda_reconstruct_fourier  -i
Runs/003545_XmippProtReconstructHighRes/extra/Iter001/images_corrected01.xmd
-o Runs/003545_XmippProtReconstructHighRes/extra/Iter001/volume01.vol
--sym c1 --weight --device 1 --thr 1' returned non-zero exit status 255
00344:   Protocol failed: Command 'xmipp_cuda_reconstruct_fourier  -i
Runs/003545_XmippProtReconstructHighRes/extra/Iter001/images_corrected01.xmd
-o Runs/003545_XmippProtReconstructHighRes/extra/Iter001/volume01.vol
--sym c1 --weight --device 1 --thr 1' returned non-zero exit status 255
00345:   FAILED: reconstruct, step 6
00346:     2019-10-31 15:43:03.639203
00347:   *** Last status is failed
00348:   ------------------- PROTOCOL FAILED (DONE 6/10)

**Comment by DStrelak** [comment]
Hello @dmaluenda ,

as we have already discussed, this issue was a bug in older version.
It should be already fixed in current devel branch of @I2PC/xmipp , namely by https://github.com/I2PC/xmipp/pull/214 and https://github.com/I2PC/xmipp/pull/210 .

I'm gonna move it there, and consider it closed.

Please reopen it if needed.
