### ISSUE TITLE
Bug with movie alignment

### ISSUE THREAD

**Issue by Vilax** [I2PC/scipion-em-xmipp#174]
Xmipp correlation alignment presents next problem:

When the option save aligned movie is enable, the output movie is not saved, but the Scipion object is created. This problem seems to be the same that this one with motioncorr

https://github.com/scipion-em/scipion-em-motioncorr/issues/27

Thanks in advance

Vilas

**Comment by DStrelak** [comment]
Hello @Vilax,

I'm using devel branches of Scipion + Xmipp.
I tried `xmipp3.tests.test_protocols_mixed_movies.TestMixedMovies`, the 'CC (write)' protocol.
In the log the aligned movie is requested (`--oaligned Runs/000447_XmippProtMovieCorr/extra/Falcon_2012_06_12-16_55_40_0_movie_aligned_movie.mrcs`), and I can see it in the directory structure. 
The summary tab also lists it as an output:
![image](https://user-images.githubusercontent.com/28389367/70551703-525be100-1b78-11ea-9edb-e0adbcd87121.png)

Please let me know how to reproduce it.

**Comment by DStrelak** [comment]
Closing (obsolete)
