### ISSUE TITLE
Random conical tilt protcol fails when there is a subset of the mics.

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion-em-xmipp#181]
It fails with:
00088:   Traceback (most recent call last):
00089:     File "/usr/local/scipion2/pyworkflow/protocol/protocol.py", line 186, in run
00090:       self._run()
00091:     File "/usr/local/scipion2/pyworkflow/protocol/protocol.py", line 237, in _run
00092:       resultFiles = self._runFunc()
00093:     File "/usr/local/scipion2/pyworkflow/protocol/protocol.py", line 233, in _runFunc
00094:       return self._func(*self._args)
00095:     File "/usr/local/scipion2/software/lib/python2.7/site-packages/xmipp3/protocols/protocol_random_conical_tilt.py", line 136, in createRctImagesStep
00096:       self._appendRctImages(class2D)
00097:     File "/usr/local/scipion2/software/lib/python2.7/site-packages/xmipp3/protocols/protocol_random_conical_tilt.py", line 188, in _appendRctImages
00098:       (angleY, angleY2, angleTilt) = angles.getAngles()
00099:   AttributeError: 'NoneType' object has no attribute 'getAngles'
00100:   Protocol failed: 'NoneType' object has no attribute 'getAngles'

I've done some research, and turns out the angles id of the anlges.sqlite goes sequencially from 1 - N regardless the mic ids and there is no micid. (generated by the assign tilt pairs)

The RCT protocol search for the angles based on the micId and they do not match.

Example:

Subset
id --> 2,3,4,6,7

assign til pair:
ids of the setOfAngles: 1,2,3,4,5

RCT:
fails for 6 (there are no angles with id 6) but actually for mic 2,3,4 is picking the wrong angle values.

**Comment by pconesa** [comment]
Scipion 2.0

**Comment by DStrelak** [comment]
I believe that this has been recently fixed in the devel branch.
