### ISSUE TITLE
Modify protocol name unit cell -> asymmetricCell

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion-em-xmipp#185]
Following the advice of the referee os Scipion model building article,  It would be better refer to this operation (extract_unit_cell) as ``extracting an asymmetric unit'' and not a “unit cell” (as there is no
crystal here)

   That is  extract_unit_cell should be extract_asymmetic_cell

**Comment by DStrelak** [comment]
@rmarabini what's the status?

**Comment by rmarabini** [comment]
Hi @DStrelak ,

  this is done I close the issue
