### ISSUE TITLE
Protocol for emdb download

### ISSUE THREAD

**Issue by rsanchezgarc** [I2PC/scipion-em-xmipp#213]
It could be something as easy as 

wget -O - ftp://ftp.ebi.ac.uk/pub/databases/emdb/structures/$1/map/emd_${ID}.map.gz| zcat  > pathToDownload/emd_${ID}.map

**Comment by delarosatrevin** [comment]
I think this is already implemented. Check the plugin for atom-structure-utils or something like this. I guess @rmarabini knows about it. ;)

**Comment by rmarabini** [comment]
Hi @delarosatrevin  y @rsanchezgarc ,

  We have implemented import sequences and import PDB files. Very long time ago I did implement 
fetch maps from EMDB in xmipp but this is lost.

 I would advice not to use wget but follow chimera approach and use urllib 
(./share/FetchEMDB/fetch_emdb_map.py).

 Actually I volunteer to implement this. It should not take longer than one day.

**Comment by albertmena** [comment]
We write down the suggestion, and we close the issue because outdated.
