### ISSUE TITLE
need a new release on pip

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion-em-xmipp#236]
```
 > error when importing from xmipp3.protocols: cannot import name 'ProtMonitor' from 'pwem.protocols' (/lmb/home/gsharov/soft/scipion3/scipion-em/pwem/protocols/__init__.py)
   File "/public/EM/Scipion/miniconda3/envs/.scipion3env/lib/python3.8/site-packages/xmipp3/protocols/protocol_metaprotocol_discrete_heterogeneity_scheduler.py", line 36, in <module>
```

**Comment by dmaluenda** [comment]
You are right. I'll do it.

Thanks!!

**Comment by dmaluenda** [comment]
Done, check it please.

Thanks a lot!

Now I will make the PRs from python3_migration to devel

**Comment by azazellochg** [comment]
```
(test) [azazello@xps13-9350 soft]$ python -m scipion installp -p scipion-em-xmipp -j 2
Scipion v3.0 () devel

Building scipion-em-xmipp ...
/home/azazello/.conda/envs/test/bin/python -m pip install scipion-em-xmipp==20.7a7
ERROR: Could not find a version that satisfies the requirement scipion-em-xmipp==20.7a7 (from versions: 1.0.0a1, 1.0.0b1, 19.3b0, 19.3.1b0, 19.3.2b0, 19.3.3b0, 19.3.3b2, 19.3.3b3, 19.3.3b4, 19.3.3b5, 19.3.3b6, 19.3.3b7, 19.3.3b8, 19.4, 19.4.1, 19.4.2, 19.4.3, 20.7a0, 20.7a1, 20.7a2, 20.7a3, 20.7a4, 20.7a5, 20.7a6)
ERROR: No matching distribution found for scipion-em-xmipp==20.7a7
```

**Comment by dmaluenda** [comment]
Weird.. try again. 

The plugin should be found. However, I've just realized on a bug compiling from XmippSrc (not in xmippDev). But if you have a working binary, it should still working.

**Comment by azazellochg** [comment]
Now it works! 7a0 is installing!


Best regards,
Grigory

--------------------------------------------------------------------------------
Grigory Sharov, Ph.D.

MRC Laboratory of Molecular Biology,
Francis Crick Avenue,
Cambridge Biomedical Campus,
Cambridge CB2 0QH, UK.
tel. +44 (0) 1223 267228 <+44%201223%20267228>
e-mail: gsharov@mrc-lmb.cam.ac.uk

**Comment by dmaluenda** [comment]
you mean 7a7, right?

**Comment by azazellochg** [comment]
Probably yes, I m sure it's using the last available

**Comment by dmaluenda** [comment]
Just FYI, that bug on the compilation of xmippSrc is fixed.

Now 'installscipion /path/to/scipion3' works installing both scipion and xmipp.
