### ISSUE TITLE
Xmipp3-CL2D fails when making Stable Core

### ISSUE THREAD

**Issue by Sacha83** [I2PC/scipion-em-xmipp#240]
In V1.2.1 (CentOS 7.5.1804), I started CL2D with 18,000 particles into recommended 91 classes using 2 MPI. This was taking too long, so I stopped the job and continued with 8 MPI. I got computed classes (0-5), computed classes_core (0-5) but not stable_core classes. The error in run.stout is:

01313:   STARTED: createOutputStep, step 9
01314:     2018-11-16 12:08:58.402710
01315:   Traceback (most recent call last):
01316:     File "/data/sbgrid/programs/x86_64-linux/scipion/1.2.1/pyworkflow/protocol/protocol.py", line 190, in run
01317:       self._run()
01318:     File "/data/sbgrid/programs/x86_64-linux/scipion/1.2.1/pyworkflow/protocol/protocol.py", line 237, in _run
01319:       resultFiles = self._runFunc()
01320:     File "/data/sbgrid/programs/x86_64-linux/scipion/1.2.1/pyworkflow/protocol/protocol.py", line 233, in _runFunc
01321:       return self._func(*self._args)
01322:     File "/data/sbgrid/programs/x86_64-linux/scipion/1.2.1/pyworkflow/em/packages/xmipp3/protocol_cl2d.py", line 312, in createOutputStep
01323:       self._fillClassesFromLevel(classes2DSet, "last", subset)
01324:     File "/data/sbgrid/programs/x86_64-linux/scipion/1.2.1/pyworkflow/em/packages/xmipp3/protocol_cl2d.py", line 517, in _fillClassesFromLevel
01325:       updateClassCallback=self._updateClass)
01326:     File "/data/sbgrid/programs/x86_64-linux/scipion/1.2.1/pyworkflow/em/data.py", line 1636, in classifyItems
01327:       classItem.append(newItem)
01328:     File "/data/sbgrid/programs/x86_64-linux/scipion/1.2.1/pyworkflow/em/data.py", line 884, in append
01329:       EMSet.append(self, image)
01330:     File "/data/sbgrid/programs/x86_64-linux/scipion/1.2.1/pyworkflow/object.py", line 1152, in append
01331:       self._insertItem(item)
01332:     File "/data/sbgrid/programs/x86_64-linux/scipion/1.2.1/pyworkflow/object.py", line 1156, in _insertItem
01333:       self._getMapper().insert(item)
01334:     File "/data/sbgrid/programs/x86_64-linux/scipion/1.2.1/pyworkflow/mapper/sqlite.py", line 726, in insert
01335:       self.db.createTables(obj.getObjDict(includeClass=True))
01336:     File "/data/sbgrid/programs/x86_64-linux/scipion/1.2.1/pyworkflow/mapper/sqlite.py", line 1061, in createTables
01337:       )""" % self.tablePrefix)
01338:   OperationalError: near "-": syntax error
01339:   Protocol failed: near "-": syntax error
01340:   FAILED: createOutputStep, step 9
01341:     2018-11-16 12:09:28.602153
01342:   ------------------- PROTOCOL FAILED (DONE 9/13)

I do have "-" in my filenames, but essentially the same job on other particles (with "-") in the name completed without error.

**Comment by albertmena** [comment]
outdated, we would need an example
