### ISSUE TITLE
TestXmippProtHelicalPArameters not working

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion-em-xmipp#26]
scipion version 2.0 074a03d
xmipp_plugin scommit 2e1012d1d02abc65153b21cace3574366b7b57dd
                                      Date:   Thu Nov 29 17:20:11 2018 +0100

ERROR:

0014:     2018-11-29 17:08:55.530028
00015:   xmipp_transform_symmetrize -i /home/roberto/sda/ScipionUserData/projects/TestXmippProtHelicalParameters/Runs/000002_ProtImportVolumes/extra/import_helix_59_4__6_7.vol -o Runs/000049_XmippProtHelicalParameters/volume_symmetrized.vol --sym dihedral --dont_wrap
00016:   Input File: /home/roberto/sda/ScipionUserData/projects/TestXmippProtHelicalParameters/Runs/000002_ProtImportVolumes/extra/import_helix_59_4__6_7.vol
00017:   Output File: Runs/000049_XmippProtHelicalParameters/volume_symmetrized.vol
00018:   Symmetry: dihedral
00019:   No group: 0
00020:   Wrap:     0
00021:   Sum:      0
00022:   Spline:   3
00023:   Segmentation fault (core dumped)
00024:   Traceback (most recent call last):
00025:     File "/home/roberto/Scipion/scipion_plugin/pyworkflow/protocol/protocol.py", line 190, in run
00026:       self._run()
00027:     File "/home/roberto/Scipion/scipion_plugin/pyworkflow/protocol/protocol.py", line 237, in _run
00028:       resultFiles = self._runFunc()
00029:     File "/home/roberto/Scipion/scipion_plugin/pyworkflow/protocol/protocol.py", line 233, in _runFunc
00030:       return self._func(*self._args)
00031:     File "/home/roberto/Scipion/scipion_plugin/software/lib/python2.7/site-packages/xmipp3/protocols/protocol_helical_parameters.py", line 86, in copyInput
00032:       self.runJob("xmipp_transform_symmetrize","-i %s -o %s --sym dihedral --dont_wrap" % (self.fnVol, self.fnVolSym))
00033:     File "/home/roberto/Scipion/scipion_plugin/pyworkflow/protocol/protocol.py", line 1190, in runJob
00034:       self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
00035:     File "/home/roberto/Scipion/scipion_plugin/pyworkflow/protocol/executor.py", line 61, in runJob
00036:       env=env, cwd=cwd, gpuList=self.getGpuList())
00037:     File "/home/roberto/Scipion/scipion_plugin/pyworkflow/utils/process.py", line 52, in runJob
00038:       return runCommand(command, env, cwd)
00039:     File "/home/roberto/Scipion/scipion_plugin/pyworkflow/utils/process.py", line 67, in runCommand
00040:       env=env, cwd=cwd)
00041:     File "/home/roberto/Scipion/scipion_plugin/software/lib/python2.7/subprocess.py", line 186, in check_call
00042:       raise CalledProcessError(retcode, cmd)
00043:   CalledProcessError: Command 'xmipp_transform_symmetrize -i /home/roberto/sda/ScipionUserData/projects/TestXmippProtHelicalParameters/Runs/000002_ProtImportVolumes/extra/import_helix_59_4__6_7.vol -o Runs/000049_XmippProtHelicalParameters/volume_symmetrized.vol --sym dihedral --dont_wrap' returned non-zero exit status 139

**Comment by dmaluenda** [comment]
The especific problem is here:

`xmipp_transform_symmetrize -i /home/roberto/sda/ScipionUserData/projects/TestXmippProtHelicalParameters/Runs/000002_ProtImportVolumes/extra/import_helix_59_4__6_7.vol -o Runs/000049_XmippProtHelicalParameters/volume_symmetrized.vol --sym dihedral --dont_wrap`

`Input File: /home/roberto/sda/ScipionUserData/projects/TestXmippProtHelicalParameters/Runs/000002_ProtImportVolumes/extra/import_helix_59_4__6_7.vol`
`Output File: Runs/000049_XmippProtHelicalParameters/volume_symmetrized.vol`
`Symmetry: dihedral`
`No group: 0`
`Wrap: 0`
`Sum: 0`
`Spline: 3`

**`Segmentation fault (core dumped)`**

**Comment by dmaluenda** [comment]
The test is passing in buildbot: http://arquimedes.cnb.csic.es:9980/#/builders/52/builds/5 -> Step 18.

I'm clossing this.
