### ISSUE TITLE
movie maxshift doesnt account for binning

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion-em-xmipp#268]
I was running motioncor2 with bin 2. Maxshift produced movies and unbinned mics sets.

**Comment by dmaluenda** [comment]
Thanks @azazellochg ,

I'm seeing that micrographs are binned, but sampling rate remain like in the original.

**Comment by azazellochg** [comment]
Yes you are right!

**Comment by dmaluenda** [comment]
I've just fixed in a branch where I'm fixing bugs derived from tests. I will make a PR with it soon.

Thx!

**Comment by dmaluenda** [comment]
Fixed in https://github.com/I2PC/scipion-em-xmipp/pull/278

Feel free to reopen if persist.
