### ISSUE TITLE
test TestRealignmentClasses uses eman package.

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion-em-xmipp#27]
This is not a good idea if we are going to pluginize. At least the test should check if eman is available and if it is not then it should no be executed

**Comment by dmaluenda** [comment]
I think it's already done.

https://github.com/I2PC/scipion-em-xmipp/blob/812e3418a435e1e2968258655100eb264d07c1bc/xmipp3/tests/test_protocols_realignment_classes.py#L33-L37

**Comment by dmaluenda** [comment]
The [test is passing [step 76]](http://arquimedes.cnb.csic.es:9980/#/builders/52/builds/5) and the check suggested is included in the code.

I'm closing this.
