### ISSUE TITLE
XmippProtCTFMicrographs error

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion-em-xmipp#28]
devel-pluginization d3d576d
scipion-em-xmipp devel
all other xmipp repos - master. xmipp recompiled using xmipp script.

```
0041:   STARTED: _estimateCTF, step 5
00042:   xmipp_ctf_estimate_from_micrograph --micrograph Runs/000113_XmippProtPreprocessMicrographs/extra/019.mrc --oroot Runs/000418_XmippProtCTFMicrographs/extra/019/xmipp_ctf --sampling_rate 7.08000404572 --defocusU 21000.000000 --defocus_range 9000.000000 --overlap 0.7 --acceleration1D  --Q0 0.1 --min_freq 0.04 --ctfmodelSize 512 --max_freq 0.45 --kV 300.0 --Cs 2.0 --pieceDim 512 --downSamplingPerformed 1.000000 --selfEstimation
00043:      2018-11-30 15:01:20.494354
00044:   XMIPP_ERROR 1: Errors on command line parameters
00045:   Unrecognized parameter: --selfEstimation
00046:   
00047:   File: core/argsparser.cpp line: 1036
00048:   For more info use --help
00049:   xmipp_ctf_estimate_from_micrograph has failed with micrograph Runs/000113_XmippProtPreprocessMicrographs/extra/019.mrc
```

**Comment by dmaluenda** [comment]
To mix different branches on xmipp repos is not a good idea...

But, yes, we can/should manage back compatibility issues like this... In fact, I added a binary in xmipp repo which return version information. However, that's all, so far....

Thanks @azazellochg !!

**Comment by azazellochg** [comment]
but devel is default branch on scipion-em-xmipp! I didnt change anything! :)

**Comment by dmaluenda** [comment]
Yes, but also for the rest xmipp-repos.

If I understood well, you are in the devel-branch for the plugin and in master-branchfor the rest-repos; and they should be in devel-branch for all repos.

**Comment by azazellochg** [comment]
Alright, I'll switch to devel then.. thanks! @dmaluenda

**Comment by azazellochg** [comment]
problem does not exist in devel. closed.
