### ISSUE TITLE
xmipp3.tests.test_protocols_localdeblur fails- missing --sym input

### ISSUE THREAD

**Issue by andreanans** [I2PC/scipion-em-xmipp#297]
The final step of TestLocalDeblur fails because xmipp_resolution_monogenic_signal is missing the --sym parameter.

If I run it from the command-line with --sym C1 it works fine. Would  it be possible to add this option to the GUI?

Thank you

Andrea

**Comment by Vilax** [comment]
This error belongs to xmipp devel in scipion3. It is fixed in the realease. My recommendation is to runt it with scipion 2 or update to the release branch

Best

Vilas
