### ISSUE TITLE
flexalign only works in gpu

### ISSUE THREAD

**Issue by Vilax** [I2PC/scipion-em-xmipp#301]
Perhaps I'm wrong, but flexalign provides the possibility of running the protocol without GPU. However, if you do that, the binaries are not found. is it possible to run flexalign without gpu?

Thanks in advance

**Comment by Vilax** [comment]
My bad, I was pointing to a wrong version of xmipp

I'm sorry

**Comment by DStrelak** [comment]
Just for a reference - yes, FlexAlign can run also without GPU. CPU version, however, supports only global alignment.
