### ISSUE TITLE
If NMA_HOME env.var. is not defined, StructureMapping test fails

### ISSUE THREAD

**Issue by dmaluenda** [I2PC/scipion-em-xmipp#31]
We are taking the MNA_HOME from the os.environ. This is causing a failure for the StructureMapping test. Can we put a default value?? Which path should be that default value?

https://github.com/I2PC/scipion-em-xmipp/blob/bd5cd4719151b8daf990a4803dffcde1739b9780/xmipp3/protocols/nma/convert.py#L58-L63

**Comment by yaizar** [comment]
fixed in f2cef303dd7a9e3e95af8ed141d543dd91cc2882
