### ISSUE TITLE
SyntaxWarning: "is" with a literal. Did you mean "=="?

### ISSUE THREAD

**Issue by DStrelak** [I2PC/scipion-em-xmipp#328]
/home/david/git/scipion3/xmipp-bundle/src/scipion-em-xmipp/xmipp3/viewers/viewer_resolution_fso.py:467: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if (COLOR_CHOICES[self.colorMap.get()] is 'other'):

(devel branch)

**Comment by dmaluenda** [comment]
Some info: https://adamj.eu/tech/2020/01/21/why-does-python-3-8-syntaxwarning-for-is-literal/
