### ISSUE TITLE
no-dim of the output movie in OF alignment, when  "apply dose filter" is set to yes

### ISSUE THREAD

**Issue by mohsenkazemi** [I2PC/scipion-em-xmipp#33]
in optical alignment, if I set "apply dose filter" to yes, the output movie has no dimension. I was wondering if you have similar report previously? or it is probably a problem with my installation. I tried with three different sets of movies.

**Comment by dmaluenda** [comment]
Thanks @mohsenkazemi , we will have a look on it.

**Comment by dmaluenda** [comment]
Hi @mohsenkazemi , sorry for late!

I'm checking this and I'm getting a good behavior for the Optical Flow when "applay dose" is set to Yes.

In which version of Scipion / Xmipp are you running?

Thx!

**Comment by dmaluenda** [comment]
I will close this, feel free to re-open if the issue persist.
