### ISSUE TITLE
Flex align and spaces in folder

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion-em-xmipp#335]
If the path to the gain has spaces (e.g.: project name has spaces and gain comes from xmipp-gain) flexalign fails.

I think it needs "" en several arguments:
https://github.com/I2PC/scipion-em-xmipp/blob/ca5bce5aaf8a1149c252c72ef9a61fcc59aa0953/xmipp3/protocols/protocol_movie_correlation.py#L228
dark, gain, oaligned at least.

**Comment by DStrelak** [comment]
Should be solved by https://github.com/I2PC/scipion-em-xmipp/pull/336
