### ISSUE TITLE
deepPostProcessing fails to create output starting from two half maps

### ISSUE THREAD

**Issue by mmmtnez** [I2PC/scipion-em-xmipp#338]
Detailed below appears the error in protocol_postProcessing_deepPostProcessing in createOutputStep
 self._defineTransformRelation(self.inputHalf1, volume)

Neural net inference
01259:   WARNING: This is xmipp_base implementation for script
01260:   deepemhancer  -i Runs/008142_XmippProtDeepVolPostProc/tmp/inputHalf1.mrc  -i2 Runs/008142_XmippProtDeepVolPostProc/tmp/inputHalf2.mrc  -o Runs/008142_XmippProtDeepVolPostProc/extra/deepPostProcess.mrc  --deepLearningModelPath /home/roberto/scipion3/software/em/xmipp/models/deepEMhancer/production_checkpoints/deepEMhancer_tightTarget.hd5  --samplingRate 1.430000 --cleaningStrengh -1.000000 -g 0 -b 8 
01261:   deepemhancer  -i Runs/008142_XmippProtDeepVolPostProc/tmp/inputHalf1.mrc  -i2 Runs/008142_XmippProtDeepVolPostProc/tmp/inputHalf2.mrc  -o Runs/008142_XmippProtDeepVolPostProc/extra/deepPostProcess.mrc  --deepLearningModelPath /home/roberto/scipion3/software/em/xmipp/models/deepEMhancer/production_checkpoints/deepEMhancer_tightTarget.hd5  --samplingRate 1.430000 --cleaningStrengh -1.000000 -g 0 -b 8 
01262:   FINISHED: deepVolPostProStep, step 2, time 2020-12-02 14:21:12.612273

ERROR:   

01263:   STARTED: createOutputStep, step 3, time 2020-12-02 14:21:13.122197
01264:   Traceback (most recent call last):
01265:     File "/home/roberto/scipion3/.scipion3/lib/python3.7/site-packages/pyworkflow/protocol/protocol.py", line 187, in run
01266:       self._run()
01267:     File "/home/roberto/scipion3/.scipion3/lib/python3.7/site-packages/pyworkflow/protocol/protocol.py", line 238, in _run
01268:       resultFiles = self._runFunc()
01269:     File "/home/roberto/scipion3/.scipion3/lib/python3.7/site-packages/pyworkflow/protocol/protocol.py", line 234, in _runFunc
01270:       return self._func(*self._args)
01271:     File "/home/roberto/scipion3/.scipion3/lib/python3.7/site-packages/xmipp3/protocols/protocol_postProcessing_deepPostProcessing.py", line 265, in createOutputStep
01272:       self._defineTransformRelation(self.inputHalf1, volume)
01273:     File "/home/roberto/scipion3/.scipion3/lib/python3.7/site-packages/pwem/protocols/protocol.py", line 154, in _defineTransformRelation
01274:       self._defineRelation(pwobj.RELATION_TRANSFORM, srcObj, dstObj)
01275:     File "/home/roberto/scipion3/.scipion3/lib/python3.7/site-packages/pyworkflow/protocol/protocol.py", line 1276, in _defineRelation
01276:       parentExt, childExt)
01277:     File "/home/roberto/scipion3/.scipion3/lib/python3.7/site-packages/pyworkflow/mapper/sqlite.py", line 433, in insertRelation
01278:       if not o.hasObjId():
01279:   AttributeError: 'NoneType' object has no attribute 'hasObjId'
01280:   Protocol failed: 'NoneType' object has no attribute 'hasObjId'
01281:   FAILED: createOutputStep, step 3, time 2020-12-02 14:21:13.179255

**Comment by rsanchezgarc** [comment]
solved in branch rsg_fix_halfs
