### ISSUE TITLE
CTF estimation fails in stream mode on 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by DStrelak** [I2PC/scipion-em-xmipp#342]
While running ctf estimation protocol (release version), I'm getting following error:
```
00011:   Traceback (most recent call last):
00012:     File "/home/david/work/scipion3/git/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 189, in run
00013:       self._run()
00014:     File "/home/david/work/scipion3/git/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 1329, in _run
00015:       self._insertAllSteps()  # Define steps for execute later
00016:     File "/home/david/work/scipion3/git/scipion-em/pwem/protocols/protocol_micrographs.py", line 141, in _insertAllSteps
00017:       self._defineCtfParamsDict()
00018:     File "/home/david/miniconda3/envs/scipion3/lib/python3.8/site-packages/xmipp3/protocols/protocol_ctf_micrographs.py", line 385, in _defineCtfParamsDict
00019:       self.getPreviousParameters()
00020:     File "/home/david/miniconda3/envs/scipion3/lib/python3.8/site-packages/xmipp3/protocols/protocol_ctf_micrographs.py", line 374, in getPreviousParameters
00021:       for ctf in self.ctfRelations.get():
00022:   TypeError: 'NoneType' object is not iterable
```

It seems to me that it's caused by ctf estimation using a micrograph from movie max shift, which has not (yet) been processed by cistem ctffind4 (i.e. sync issue on input data).

Workaround seems to be to 'Reset from here' and then 'Continue workflow'.

Below is a screenshot of my workflow (notice that xmipp ctf estimation has movie maxshift and ctffind4 as input):
![image](https://user-images.githubusercontent.com/28389367/102776670-722f0300-438f-11eb-9e34-df83cd215671.png)

**Comment by DStrelak** [comment]
Just  a note - I have seen similar issue with other protocols that have transitive dependency on input, namely cistem particle picker

**Comment by DaniDelHoyo** [comment]
@DStrelak , this issue is solved already. In the current implementation I have checked that the protocol will wait for the corresponding CTF before processing a micrograph.
