### ISSUE TITLE
protocol center particles does not preserve coord micname

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion-em-xmipp#346]
The polishing error was reported by Dmitry Semchonok.

For relion polishing micname preservation is essential to trace back particles to aligned movies. Xmipp protocol does not keep it that cause polishing to fail:
![image](https://user-images.githubusercontent.com/6952870/103366469-a5be0b80-4aba-11eb-9818-17cb88406ad7.png)

**Comment by pconesa** [comment]
Thanks @azazellochg . This is already happening in a user machine. I'd suggest to patch master.

**Comment by pconesa** [comment]
I've assigned 3 of you but not sure who should be assigned.

**Comment by DStrelak** [comment]
Should be solved
