### ISSUE TITLE
Protocol 'xmipp - subtract projection'

### ISSUE THREAD

**Issue by JuhaHuiskonen** [I2PC/scipion-em-xmipp#356]
I am trying to run 'xmipp - subtract projection' in Scipion 3.0.7.  It fails with the following error:

00001:   RUNNING PROTOCOL -----------------
00002:   Hostname: xxxxxx
00003:   PID: 8268
00004:   pyworkflow: 3.0.8
00005:   plugin: orphan
00006:   currentDir: xxxxxx
00007:   workingDir: Runs/005763_XmippProtSubtractProjection
00008:   runMode: Restart
00009:             MPI: 1
00010:         threads: 64
00011:   'NoneType' object has no attribute 'Plugin' LegacyProtocol installation couldn't be validated. Possible cause could be a configuration issue. Try to run scipion config.
00012:   Protocol has validation errors:
00013:   'NoneType' object has no attribute 'Plugin' LegacyProtocol installation couldn't be validated. Possible cause could be a configuration issue. Try to run scipion config.
00014:   ------------------- PROTOCOL FAILED (DONE 0/0)

**Comment by rmarabini** [comment]
Hi @DStrelak, please delete "'xmipp - subtract projection" it does not make sense to maintain it. I guess @JuhaHuiskonen is trying to use it because "relion subtract projection" does not longer work with an arbitrary set of particles. I am modifying "relion subtract projection" so it has all the functionally available in Scipion 2 version. I will let you know when I am done.

**Comment by JuhaHuiskonen** [comment]
Hi @rmarabini indeed I would use 'relion - subtract projection', if it worked with subsets of particles.

**Comment by DStrelak** [comment]
Hi @JuhaHuiskonen , is this a valid solution for you?
@rmarabini , do we have any workaround meanwhile?

**Comment by JuhaHuiskonen** [comment]
Hi @DStrelak yes, if the relion version can be made to work with any set of particles then it would be a valid solution for me (my dataset is so large that a single job requires more than the time limit on the cluster - so the only option seems to be to split the SetOfParticles from RELION).

**Comment by DStrelak** [comment]
> my dataset is so large that a single job requires more than the time limit on the cluster 

Have you tried / is it applicable in your case to use pwem-(split)subset protocol?
There is also xmipp_extract_subset program, which, unlike the split protocol, also extracts the particles from the stack file (i.e. you don't need the original stack file with all particles with your newly created smaller metadata file).

**Comment by rmarabini** [comment]
I do not think we have any alternative.

**Comment by JuhaHuiskonen** [comment]
@DStrelak I have tried splitting.  But subsets are not compatible with relion subtraction, as its output is relion - auto refine 3D protocol, not a SetOfParticles produced by subset/split.
