### ISSUE TITLE
ctf consensus issues

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion-em-xmipp#39]
I just ran the protocol in non-streaming more. It worked, but:
1) Summary shows: 'NoneType' object has no attribute '_objParentId'
2) Methods show: ERROR generating methods info: 'NoneType' object has no attribute 'replace'

**Comment by dmaluenda** [comment]
This have been fixed in https://github.com/I2PC/scipion-em-xmipp/pull/44/commits/a9adfbde91a5978867335cd822d86caa6bc09d49 .
