### ISSUE TITLE
CL2D protocol is shown as running, but there's no progress

### ISSUE THREAD

**Issue by DStrelak** [I2PC/scipion-em-xmipp#414]
Originally reported here:
https://github.com/scipion-em/scipion-pyworkflow/issues/258#issuecomment-855177509

**Comment by DStrelak** [comment]
@shuaishuairuirui
Let's try to debug this.

0. Terminate the CL2D protocol (via right-click -> `Stop from here`)
1. Please, turn off scipion completely, then run it again.
Do you see any errors reported in your terminal?
2. Open your project
3. Click on `Project->Debug mode` (top left corner), then click on `Refresh` in the top right corner
4. Right-click on the CL2D protocol -> `Copy` and then `Execute` the protocol
Do you see any errors reported in your terminal?
Is the protocol running? Does it finish?
Please copy here / attach the content of the `Output Log -> run.stdout` tab

**Comment by shuaishuairuirui** [comment]
> @shuaishuairuirui
> Let's try to debug this.
> 
>     1. Terminate the CL2D protocol (via right-click -> `Stop from here`)
> 
>     2. Please, turn off scipion completely, then run it again.
>        Do you see any errors reported in your terminal?
> 
>     3. Open your project
> 
>     4. Click on `Project->Debug mode` (top left corner), then click on `Refresh` in the top right corner
> 
>     5. Right-click on the CL2D protocol -> `Copy` and then `Execute` the protocol
>        Do you see any errors reported in your terminal?
>        Is the protocol running? Does it finish?
>        Please copy here / attach the content of the `Output Log -> run.stdout` tab

Hi @DStrelak 

I had do the steps as you said.And I didn't get err message like the screenshot.

The run.stdout is that:
File 'Runs/001516_XmippProtCL2D/logs/run.stdout' doesn't exist00001:   RUNNING PROTOCOL -----------------
00002:   Hostname: localhost.localdomain
00003:   PID: 42677
00004:   pyworkflow: 3.0.14
00005:   plugin: xmipp3
00006:   currentDir: /data0/x/test
00007:   workingDir: Runs/001516_XmippProtCL2D
00008:   runMode: Continue
00009:             MPI: 32
00010:         threads: 1
00011:   len(steps) 5 len(prevSteps) 0 
00012:    Starting at step: 1
00013:    Running steps 
00014:   STARTED: convertInputStep, step 1, time 2021-06-05 18:45:19.454942
00015:   FINISHED: convertInputStep, step 1, time 2021-06-05 18:45:20.843168
00016:   STARTED: runJob, step 2, time 2021-06-05 18:45:20.860737
00017:    mpirun -np 32  `which xmipp_mpi_classify_CL2D` -i Runs/001516_XmippProtCL2D/tmp/input_particles.xmd --odir Runs/001516_XmippProtCL2D/extra --oroot level --nref 4 --iter 10  --distance correlation --classicalMultiref --nref0 4

![image](https://user-images.githubusercontent.com/59869039/120889398-6f6b5600-c62f-11eb-93f6-b78d298b801d.png)

**Comment by shuaishuairuirui** [comment]
![Screenshot from 2021-06-06 12-03-57](https://user-images.githubusercontent.com/59869039/120912119-24008880-c6bf-11eb-878e-a24099f0b55f.png)
Is this a problem?When I install scipion I meet this warning.I don't know what image library I should install.Can you give me some advise.Thanks very much.

**Comment by DStrelak** [comment]
> Is this a problem?

Yes. 
You seem to have corrupted installation of Xmipp (as indicated by `please install Xmipp ...`. I'm not sure how Scipion can report that Xmipp is missing, but still show you its plugins and not throw error due to missing binaries when you execute the CL2D protocol.
I would recommend you to complete remove Scipion from your system, including all virtual environments you might have created with it, and install it from scratch.

**Comment by DStrelak** [comment]
`CL2D` is not GPU accelerated protocol

**Comment by DStrelak** [comment]
Hi @shuaishuairuirui, 
any update from your side?

**Comment by albertmena** [comment]
Closed the issue because is a local problem and without feedback
