### ISSUE TITLE
deep consensus picking failng

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion-em-xmipp#426]
I'm running xmipp in devel.

Just got this error:

00443:   Using TensorFlow backend.
00444:   Traceback (most recent call last):
00445:     File "/home/tomo/scipion3/software/bindings/xmipp_base.py", line 107, in tryRun
00446:       self.run()
00447:     File "/home/tomo/scipion3/software/em/xmipp/bin/xmipp_deep_consensus", line 163, in run
00448:       ScriptDeepScreeningTrain.predictWorker(**scoringArgs)
00449:     File "/home/tomo/scipion3/software/em/xmipp/bin/xmipp_deep_consensus", line 235, in predictWorker
00450:       predictDataManager = DataManager(posSetDict=predictDict, negSetDict=None)
00451:     File "/home/tomo/scipion3/software/em/xmipp/pylib/xmippPyModules/deepConsensusWorkers/deepConsensus_deepLearning1.py", line 284, in __init__
00452:       self.mdListTrue, self.fnMergedListTrue, self.weightListTrue, self.nTrue, self.shape= self.colectMetadata(posSetDict)
00453:     File "/home/tomo/scipion3/software/em/xmipp/pylib/xmippPyModules/deepConsensusWorkers/deepConsensus_deepLearning1.py", line 321, in colectMetadata
00454:       I.read(mdObject.getValue(xmippLib.MDL_IMAGE, mdObject.firstObject()))
00455:   xmipp.XmippError: Cannot access file 'None'. It doesn't exist
00456:   Traceback (most recent call last):
00457:     File "/home/tomo/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 201, in run
00458:       self._run()
00459:     File "/home/tomo/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 252, in _run
00460:       resultFiles = self._runFunc()
00461:     File "/home/tomo/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 248, in _runFunc
00462:       return self._func(*self._args)
00463:     File "/home/tomo/scipion3/xmipp-bundle/src/scipion-em-xmipp/xmipp3/protocols/protocol_screen_deepConsensus.py", line 1049, in predictCNN
00464:       self.runJob('xmipp_deep_consensus', args, numberOfMpi=1,
00465:     File "/home/tomo/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 1388, in runJob
00466:       self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
00467:     File "/home/tomo/scipion3/scipion-pyworkflow/pyworkflow/protocol/executor.py", line 65, in runJob
00468:       process.runJob(log, programName, params,
00469:     File "/home/tomo/scipion3/scipion-pyworkflow/pyworkflow/utils/process.py", line 52, in runJob
00470:       return runCommand(command, env, cwd)
00471:     File "/home/tomo/scipion3/scipion-pyworkflow/pyworkflow/utils/process.py", line 67, in runCommand
00472:       check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr,
00473:     File "/home/tomo/anaconda3/envs/scipion3/lib/python3.8/subprocess.py", line 364, in check_call
00474:       raise CalledProcessError(retcode, cmd)
00475:   subprocess.CalledProcessError: Command ' xmipp_deep_consensus  -n Runs/009654_XmippProtScreenDeepConsensus/extra/nnetData --mode score -i Runs/009654_XmippProtScreenDeepConsensus/extra/particles_OR_partial.xmd -o Runs/009654_XmippProtScreenDeepConsensus/particles_partial.xmd  -g 3' returned non-zero exit status 1.

**Comment by DStrelak** [comment]
> 00455: xmipp.XmippError: Cannot access file 'None'. It doesn't exist

@pconesa , can you please have a look at the protocols providing the picked particles and make sure there's no report from them? From the log, it seems that there was some file missing at the input of the deep consensus. So either deep consensus failed to create it, or did not validate that the 'input protocol' generates such a file. 

Is this a test case / can you provide us with the project folder?

**Comment by pconesa** [comment]
Hi David! Input picking protocols seems fine. I do not see anything strange with their output. There is a suspicious "Predicting on 0 true particles" message in the log:


> Epoch 00023: ReduceLROnPlateau reducing learning rate to 1.0000000000000001e-07.
00846:   Epoch 1/22
00847:   FINISHED: trainCNN, step 20, time 2021-08-06 14:19:25.763091
00848:   STARTED: endTrainingStep, step 21, time 2021-08-06 14:19:27.709654
00849:   FINISHED: endTrainingStep, step 21, time 2021-08-06 14:19:27.714417
00850:   STARTED: predictCNN, step 22, time 2021-08-06 14:19:32.174814
00851:   Creating set of particles in Runs/009654_XmippProtScreenDeepConsensus/extra/particles_OR_partial.xmd
00852:   Predicting on 634614 true particles
00853:    xmipp_deep_consensus  -n Runs/009654_XmippProtScreenDeepConsensus/extra/nnetData --mode score -i Runs/009654_XmippProtScreenDeepConsensus/extra/particles_OR_partial.xmd -o Runs/009654_XmippProtScreenDeepConsensus/particles_partial.xmd  -g 3
00854:   WARNING: This is xmipp_base implementation for script
00855:   mode 2: scoring
00856:   SCORING ARGS: {'netDataPath': 'Runs/009654_XmippProtScreenDeepConsensus/extra/nnetData', 'predictDict': {'Runs/009654_XmippProtScreenDeepConsensus/extra/particles_OR_partial.xmd': 1}, 'outParticlesPath': 'Runs/009654_XmippProtScreenDeepConsensus/particles_partial.xmd', 'posTestDict': None, 'negTestDict': None, 'gpuToUse': 3, 'numberOfThreads': None}
00857:   updating environ to select gpus: 3
00858:   ['Runs/009654_XmippProtScreenDeepConsensus/extra/particles_OR_partial.xmd']
00859:   loading model Runs/009654_XmippProtScreenDeepConsensus/extra/nnetData/tfchkpoints_0/deepModel.hdf5
00860:   predicting with model 1/3
00861:   prediction done
00862:   loading model Runs/009654_XmippProtScreenDeepConsensus/extra/nnetData/tfchkpoints_1/deepModel.hdf5
00863:   predicting with model 2/3
00864:   prediction done
00865:   loading model Runs/009654_XmippProtScreenDeepConsensus/extra/nnetData/tfchkpoints_2/deepModel.hdf5
00866:   predicting with model 3/3
00867:   prediction done
00868:   FINISHED: predictCNN, step 22, time 2021-08-06 14:48:50.492529
00869:   STARTED: endPredictingStep, step 23, time 2021-08-06 14:48:51.220838
00870:   FINISHED: endPredictingStep, step 23, time 2021-08-06 14:48:51.225675
00871:   STARTED: createOutputStep, step 24, time 2021-08-06 14:48:51.234883
00872:   Creating new outputParticles set
00873:   Creating new outputCoordinates set
00874:   FINISHED: createOutputStep, step 24, time 2021-08-06 14:52:36.869176
00875:   STARTED: predictCNN, step 25, time 2021-08-06 14:52:37.654513
00876:   Creating set of particles in Runs/009654_XmippProtScreenDeepConsensus/extra/particles_OR_partial.xmd
00877:   Predicting on 0 true particles
00878:    xmipp_deep_consensus  -n Runs/009654_XmippProtScreenDeepConsensus/extra/nnetData --mode score -i Runs/009654_XmippProtScreenDeepConsensus/extra/particles_OR_partial.xmd -o Runs/009654_XmippProtScreenDeepConsensus/particles_partial.xmd  -g 3
00879:   WARNING: This is xmipp_base implementation for script
00880:   mode 2: scoring
00881:   SCORING ARGS: {'netDataPath': 'Runs/009654_XmippProtScreenDeepConsensus/extra/nnetData', 'predictDict': {'Runs/009654_XmippProtScreenDeepConsensus/extra/particles_OR_partial.xmd': 1}, 'outParticlesPath': 'Runs/009654_XmippProtScreenDeepConsensus/particles_partial.xmd', 'posTestDict': None, 'negTestDict': None, 'gpuToUse': 3, 'numberOfThreads': None}
00882:   updating environ to select gpus: 3
00883:   Protocol failed: Command ' xmipp_deep_consensus  -n Runs/009654_XmippProtScreenDeepConsensus/extra/nnetData --mode score -i Runs/009654_XmippProtScreenDeepConsensus/extra/particles_OR_partial.xmd -o Runs/009654_XmippProtScreenDeepConsensus/particles_partial.xmd  -g 3' returned non-zero exit status 1.
00884:   FAILED: predictCNN, step 25, time 2021-08-06 14:52:40.320516
