### ISSUE TITLE
Possibly incorrectly categorized protocols

### ISSUE THREAD

**Issue by DStrelak** [I2PC/scipion-em-xmipp#427]
Please verify that the following protocols are in the right categories in the Scipion protocol tree

1.  ML2D (`Protocols SPA - 2D - Classify - More`)
2. Kerdensom (`Protocols SPA - 2D - Classify - More`)

**Comment by cossorzano** [comment]
That's correct

**Comment by DStrelak** [comment]
> That's correct

Even the `More` part? Why is it so 'hidden'?

**Comment by cossorzano** [comment]
Because they are backup methods and not the ones that should be promoted.
