### ISSUE TITLE
Modifications needed to compile xmipp  in debian-11

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion-em-xmipp#436]
This is what I needed to do in order to compile xmipp in debian 11:

 add conda library  to ld_library_path 
use gcc/g++ version 9 instead of the default one 10

     export GXX=g++-9
     export CC=gcc-9
     export LD_LIBRARY_PATH=/home/roberto/.conda/envs/scipion3/lib

I think path to conda lib should be included by default

**Comment by DStrelak** [comment]
Hi @rmarabini , 

why did you have to add LD_LIBRARY_PATH? It is not recommended to change it with conda, because it might mess up the environment pretty badly. 
Why did you have to change the compiler?

**Comment by albertmena** [comment]
Xmipp tested in debian 11 and works properly
