### ISSUE TITLE
Probably there is a bug in xmipp3.conver.convert.py line 850

### ISSUE THREAD

**Issue by rsanchezgarc** [I2PC/scipion-em-xmipp#49]
I think that
850        getPosFunc = lambda coord: coord.getPostion()

is misspelled
and should be 
        getPosFunc = lambda coord: coord.getPosition()

**Comment by dmaluenda** [comment]
mmmm, yes, it seems a mistake...

https://github.com/I2PC/scipion-em-xmipp/blob/758fc5905d9d5fcb25595b49fb06cc45927874f7/xmipp3/convert/convert.py#L849

**Comment by dmaluenda** [comment]
I've fixed it in https://github.com/I2PC/scipion-em-xmipp/commit/58e7524972c9b13e87ea3cceb5f7909f60b4c160
