### ISSUE TITLE
readSetOfParticles with "extralabels" arg is very slow

### ISSUE THREAD

**Issue by EstrellaFG** [I2PC/scipion-em-xmipp#537]
`readSetOfParticles()` method (in xmipp3>convert>convert.py) with arg `extraLabels` is very slow: trying with same data it is inmediate **without** extralabels, but it takes seven minutes **with** argument extraLabels

**Comment by pconesa** [comment]
Hi! This goes straight into the python binding. I'm useless here.

Either someone review that part (not me)
Or someone, replace Metadata with emTable.

Not me either.

**Comment by EstrellaFG** [comment]
Update: read and write set of particles is being modifyied to be implemented with EMTables
