### ISSUE TITLE
protocol_deep_align not reachable in Scipion

### ISSUE THREAD

**Issue by EstrellaFG** [I2PC/scipion-em-xmipp#542]
protocol_deep_align is not in `protocols _init_` and thus, it is not reachable in Scipion. Not sure if this is an intended behaviour or not

**Comment by erneyramirez** [comment]
We are still testing with this protocol. It is intentional, yes

**Comment by EstrellaFG** [comment]
I have checked with @erneyramirez and this is *not* the protocol which is still being tested as he wrote above. @cossorzano do you know if this protocol (that is from Amaya) is finished and working and thus should be accesible in Scipion or not?? (if yes, it only need to be added to `protocols/__init__.py`).

**Comment by EstrellaFG** [comment]
deprecated protocol
