### ISSUE TITLE
protocol_split_volume_hierarchical_cluster error

### ISSUE THREAD

**Issue by gemapatricia** [I2PC/scipion-em-xmipp#547]
If you try to run protocol `split volume hierarchical` in Scipion, it gives the following error:

13704:     File "/home/pherrera/scipion3/software/bindings/xmipp_base.py", line 527, in readInfoField
13705:       mdInfo = MetaData("%s@%s" % (block, os.path.join(fnDir, xmdFile)))
13706:   xmipp.XmippError: FileName::isMetaData: File: 'Runs/000101_XmippProtSplitVolumeHierarchical/extra/iterInfo.xmd' does not exist
13707:   Protocol failed: FileName::isMetaData: File: 'Runs/000101_XmippProtSplitVolumeHierarchical/extra/iterInfo.xmd' does not exist

**Comment by EstrellaFG** [comment]
deprecate in next xmipp day

**Comment by EstrellaFG** [comment]
https://github.com/I2PC/scipion-em-xmipp/pull/700
