### ISSUE TITLE
scikit-learn update

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion-em-xmipp#554]
Hi, are there any plans to update this requirement? 
https://github.com/I2PC/scipion-em-xmipp/blob/cbc9d55aaaa401a51d8ce6b973575bc5ac127080/requirements.txt#L1
scikit-learn 0.22.1 doesn't support python >3.8 so scipion cant be used with new python

Related to https://github.com/scipion-em/scipion-pyworkflow/pull/350

**Comment by azazellochg** [comment]
I can compile devel xmipp without cuda/opencv with the latest scikit-learn (1.1.1)

**Comment by albertmena** [comment]
Thanks [azazellochg](https://github.com/azazellochg),
Yes we can do it, noted.

**Comment by azazellochg** [comment]
Hi, any update on this?

**Comment by albertmena** [comment]
https://github.com/I2PC/scipion-em-xmipp/pull/572

**Comment by albertmena** [comment]
The deepLearningToolKit enviroments use this library, there will be a[ new enviroment ](https://github.com/I2PC/scipion-em-xmipp/issues/637)(0.4) with all the libraries updated.

**Comment by azazellochg** [comment]
it is still there https://github.com/I2PC/scipion-em-xmipp/blob/eacb33439c0be728ce7fb38cd614bf52d0001a0e/requirements.txt#L2

**Comment by oierlauzi** [comment]
AFAIK, it has been updated for devel:
https://github.com/I2PC/scipion-em-xmipp/blob/devel/requirements.txt

**Comment by azazellochg** [comment]
That's awesome news!
