### ISSUE TITLE
Validate there is a mask in deepres

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion-em-xmipp#563]
A user reported today an error that could have been easily avoided if the Mask is mandatory. This is his report:

Dear Scipion user group,

I installed Xmipp3 and deep learning toolkit however, after I import the volume then call the local deepres, I had this error as below:

00001:   Traceback (most recent call last):
00002:     File "/opt/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 202, in run
00003:       self._run()
00004:     File "/opt/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 253, in _run
00005:       resultFiles = self._runFunc()
00006:     File "/opt/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 249, in _runFunc
00007:       return self._func(*self._args)
00008:     File "/home/hong/scipion-em-xmipp/xmipp3/protocols/protocol_resolution_deepres.py", line 144, in convertInputStep
00009:       self.maskFn = self.Mask.get().getFileName()
00010:   AttributeError: 'NoneType' object has no attribute 'getFileName'
00011:   Protocol failed: 'NoneType' object has no attribute ‘getFileName'

However, MonoRes works fine. Any tips to overcome this error?

**Comment by albertmena** [comment]
Fixed: https://github.com/I2PC/scipion-em-xmipp/pull/564
