### ISSUE TITLE
Volume crop resize and sampling rate in the mrc headers

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion-em-xmipp#573]
Hi, crop resize is not updating the headers fo the mrc file it generates.
![image](https://user-images.githubusercontent.com/785633/195651899-ccb09c32-173e-49aa-8987-8a27cf4a9c7f.png)

**Comment by pconesa** [comment]
Output is a scaled volume of 100x100x100 that should have 2.38 of sampling rate. The "output_volume-mrc" is still keeping the original sr 0.65 in the headers

**Comment by albertmena** [comment]
What options are you setting in the protocol? The "Resize option" is Sampling Rate?

**Comment by pconesa** [comment]
Any option that will imply a scale will affect this. Either "Sampling rate" or "dimensions" not sure about others.

**Comment by EstrellaFG** [comment]
Hi @pconesa, in the test works fine with different options (see attached screenshots). Are you sure that your volume is a real volume or a stack? If you upload your volume and the form (options selected) we can check it with it.
![Screenshot from 2022-12-02 12-51-47](https://user-images.githubusercontent.com/30145413/205287153-197414f4-33b6-4b67-8d4a-48f11124aba7.png)
![Screenshot from 2022-12-02 12-50-48](https://user-images.githubusercontent.com/30145413/205287156-c642814f-e4e9-47ec-851d-3e80a7b6d2e8.png)

![Screenshot from 2022-12-02 12-52-36](https://user-images.githubusercontent.com/30145413/205287152-5f489a5e-ca2c-4650-9112-b8405410d5b4.png)

**Comment by EstrellaFG** [comment]
The same error was reported in https://github.com/I2PC/xmipp/issues/706 and the issue was closed because it seems to be fixed now, as in the checks that I posted in last comment. I have re-checked now and efectively, it seems that is fixed.
