### ISSUE TITLE
xmipp3 - helical symmetry

### ISSUE THREAD

**Issue by DmitrySemchonok** [I2PC/scipion-em-xmipp#575]
Dear colleagues, 

Although the process uses threads, the processing speed is veeeery slow. 

Could you please have a look and fix the processing speed?
I used the volume 320x320x320, pixel size 1.567A/pix with 10 Threads - the processing time took more than 10 hours

Thank you!

Kind regards,
Dmitry
<img width="1035" alt="Screenshot 2022-10-18 at 09 19 06" src="https://user-images.githubusercontent.com/21281315/196362845-35a74b00-499d-48b7-a13a-7f9970d005c1.png">

**Comment by cossorzano** [comment]
I thought that threads were not used, but they are. It takes time simply because it is a large volume and there is a fine sampling of the helical parameters.
