### ISSUE TITLE
Problem with XmippProtTriggerData

### ISSUE THREAD

**Issue by olofsvensson** [I2PC/scipion-em-xmipp#577]
Hi,

I get systematically this error from XmippProtTriggerData when triggered from ProtRelionExtractParticles :

> 00001:   Traceback (most recent call last):
> 00002:     File "/opt/pxsoft/scipion/v3_20221019/ubuntu20.04/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 202, in run
> 00003:       self._run()
> 00004:     File "/opt/pxsoft/scipion/v3_20221019/ubuntu20.04/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 1453, in _run
> 00005:       self._runSteps(startIndex)
> 00006:     File "/opt/pxsoft/scipion/v3_20221019/ubuntu20.04/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 1295, in _runSteps
> 00007:       self._stepsExecutor.runSteps(self._steps,
> 00008:     File "/opt/pxsoft/scipion/v3_20221019/ubuntu20.04/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/executor.py", line 131, in runSteps
> 00009:       stepsCheckCallback()
> 00010:     File "/opt/pxsoft/scipion/v3_20221019/ubuntu20.04/miniconda3/envs/scipion3/lib/python3.8/site-packages/xmipp3/protocols/protocol_trigger_data.py", line 121, in _stepsCheck
> 00011:       self._checkNewOutput()
> 00012:     File "/opt/pxsoft/scipion/v3_20221019/ubuntu20.04/miniconda3/envs/scipion3/lib/python3.8/site-packages/xmipp3/protocols/protocol_trigger_data.py", line 179, in _checkNewOutput
> 00013:       self.stopWait()
> 00014:     File "/opt/pxsoft/scipion/v3_20221019/ubuntu20.04/miniconda3/envs/scipion3/lib/python3.8/site-packages/xmipp3/protocols/protocol_trigger_data.py", line 356, in stopWait
> 00015:       f = open(self._getStopConnectingFilename(), 'w')
> 00016:   TypeError: expected str, bytes or os.PathLike object, not NoneType

The function `_getStopConnectingFilename` https://github.com/I2PC/scipion-em-xmipp/blob/068833787f5ef5bb69c171e2cea15bc00f84228a/xmipp3/protocols/protocol_trigger_data.py#L359 returns None, which makes the method `stopWait` crash since the file name is None.

Is this a bug or could it be that the function `_getStopConnectingFilename` should always return a string and never None?

**Comment by danielmarchan3** [comment]
Hi @olofsvensson, 

It is not an error itself cause you are not linking any Trigger protocol (see the image uploaded to see the correct form) and that is why it is giving you this error. It is true that I have to add a validate to make sure that this does not happens. T

![trigger_protocol_correctly](https://user-images.githubusercontent.com/35836096/197170025-a91f670b-e230-433d-b81f-169bfa931c8d.png)

Thank you for the comment, I will change it.
