### ISSUE TITLE
Tolerate spaces in at least XmippProtConvertPdb

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion-em-xmipp#584]
This is a common error and we may do something about it at import time, fixing this should be as easy as wrapping the argument with " " --> "Runs/000150_XmippProtConvertPdb/extra/3D Molecular Model_RC-LH1"

00035:     File “/home/user/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py”, line 202, in run
00036:       self._run()
00037:     File “/home/user/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py”, line 253, in _run
00038:       resultFiles = self._runFunc()
00039:     File “/home/user/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py”, line 249, in _runFunc
00040:       return self._func(*self._args)
00041:     File “/home/user/Data/Software/xmipp/src/scipion-em-xmipp/xmipp3/protocols/protocol_convert_pdb.py”, line 147, in convertPdbStep
00042:       self.runJob(program, args)
00043:     File “/home/user/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py”, line 1480, in runJob
00044:       self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
00045:     File “/home/user/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/executor.py”, line 65, in runJob
00046:       process.runJob(log, programName, params,
00047:     File “/home/user/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/utils/process.py”, line 55, in runJob
00048:       return runCommand(command, env, cwd)
00049:     File “/home/user/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/utils/process.py”, line 70, in runCommand
00050:       check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr,
00051:     File “/home/user/miniconda3/envs/scipion3/lib/python3.8/subprocess.py”, line 364, in check_call
00052:       raise CalledProcessError(retcode, cmd)
00053:   subprocess.CalledProcessError: Command ' xmipp_volume_from_pdb -i Runs/000056_ProtImportPdb/extra/3D Molecular Model_RC-LH1.pdb --sampling 0.828500 -o Runs/000150_XmippProtConvertPdb/extra/3D Molecular Model_RC-LH1 --centerPDB’ returned non-zero exit status 1.
00054:   Protocol failed: Command ' xmipp_volume_from_pdb -i Runs/000056_ProtImportPdb/extra/3D Molecular Model_RC-LH1.pdb --sampling 0.828500 -o Runs/000150_XmippProtConvertPdb/extra/3D Molecular Model_RC-LH1 --centerPDB’ returned non-zero exit status 1.
I

**Comment by albertmena** [comment]
@pconesa @DavidHerreros could you check if the issues was fixed?

**Comment by albertmena** [comment]
@MartinSalinas98 could you check it and if necessary add to the https://github.com/I2PC/scipion-em-xmipp/pull/702 ?
Thanks

**Comment by MartinSalinas98** [comment]
> @MartinSalinas98 could you check it and if necessary add to the #702 ? Thanks

This is already present in" convert a pdb" protocol, thus, there is no need to add it.
