### ISSUE TITLE
monoRes gives vol0Fn missing

### ISSUE THREAD

**Issue by teret33** [I2PC/scipion-em-xmipp#606]
When I use the monoRes program to calculate the local resolution of Cryo-EM Maps I get the

> 'XmippProtMonoRes' object has no attribute 'vol0Fn'

error code.

Please help resolve his issue. I have the latest scipion installation. I have XMipp installed without CUDA. I use masks generated by Xmipp and I use 4 cores to run the program.

**Comment by jamesmkrieger** [comment]
Are you sure you're using the latest xmipp? It looks like this was fixed in June 2021

**Comment by teret33** [comment]
I get this error message:

> 00024:   Traceback (most recent call last):
> 00025:     File "/home/teret/miniconda/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 202, in run
> 00026:       self._run()
> 00027:     File "/home/teret/miniconda/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 253, in _run
> 00028:       resultFiles = self._runFunc()
> 00029:     File "/home/teret/miniconda/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 249, in _runFunc
> 00030:       return self._func(*self._args)
> 00031:     File "/home/teret/miniconda/envs/scipion3/lib/python3.8/site-packages/xmipp3/protocols/protocol_resolution_monogenic_signal.py", line 272, in resolutionMonogenicSignalStep
> 00032:       params = ' --vol %s' % self.vol0Fn
> 00033:   AttributeError: 'XmippProtMonoRes' object has no attribute 'vol0Fn'
> 00034:   Protocol failed: 'XmippProtMonoRes' object has no attribute 'vol0Fn'

I'm sure I have the most recent version of xmipp.

**Comment by Vilax** [comment]
@teret33. thanks for reporrting the error log.

Hmm, the error seems weird. 

This is a blind shot... Could be that you checked the use of half maps, and then you regret that decision checking the use of a single map? That could explain this error for which, I've already discovered that the protocol is not protected. 

Can you check the window form (or paste an screenshot), and see if you checked: use half maps. I mean I would like to see this window: 
![imagen](https://user-images.githubusercontent.com/12271438/212718726-b0bbc35c-b5e1-4737-9002-1c188b2a2fbb.png)

and this window:

![imagen](https://user-images.githubusercontent.com/12271438/212718795-9d7d01b5-55a2-479a-b426-e4d1b644a711.png)

and

![imagen](https://user-images.githubusercontent.com/12271438/212718837-de666715-da36-4a66-b796-17e88981f3a1.png)

Also, I would recommend to make a copy of the protocol.

If you want I am also available for a video call or you can send me the data and check.

Best
