### ISSUE TITLE
protocol xmipp3-reconstruct fourier doesn't seem to work properly

### ISSUE THREAD

**Issue by mmmtnez** [I2PC/scipion-em-xmipp#634]
Reconstructions seem to be completely defocussed, even using the param --useCTF. I have already testd the param Approximative version and the result is still the same. Nevertheless, the test passes without problem. I recommend to run in paralell this protocol and the relion-reconstruct protocol with the same data.

**Comment by EstrellaFG** [comment]
Hi @mmmtnez, in the new version (CUDA) that flag is not available, thus, you should use the protocol correct_wiener before to correct the CTF and then perform the reconstruction. If you want to use --useCTF, you should use the legacy version (in advanced params, but then you can not use options approximates, GPU and threads)
