### ISSUE TITLE
deepLearningToolKit installation enviroments

### ISSUE THREAD

**Issue by albertmena** [I2PC/scipion-em-xmipp#637]
- Libraries outofdate (tensorflow)
- Installation steps not clear
- Hi time consumed in the installation
- Some bugs like:

> 
> Getting this error when trying to install Xmipp DeepLearningToolkit: 
> "ERROR: No matching distribution found for numpy==1.23.0"
> And it looks like numpy v1.21.6 is the newest possible candidate. I am running conda-23.3.0. 
> 
> From inside the xmipp_DLTK_v0.3 anaconda environment I can see that this command is tried executed: 
> "pip install numpy==1.23.0 numpy==1.23.0 numpy==1.23.0 numpy==1.23.0 numpy==1.23.0"
>

**Comment by oierlauzi** [comment]
We standardized xmipp conda environment creation by using a [yml specification of the requirements](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file). This solves some installation bugs and makes code more clear. Installation times are not improved in principle. @MartinSalinas98 is working on an updated version of DLTK conda environment.

**Comment by albertmena** [comment]
These are the protocols using DLTK_v0.3 and their tests:

- protocol_screen_deeplearning
scipion3 tests xmipp3.tests.test_protocols_xmipp_2d.TestXmippScreenDeepLearning
- protocol_deep_denoising
scipion3 tests xmipp3.tests.test_protocol_deep_denoising.TestDeepDenoising
- protocol_resolution_deepres
scipion3 tests xmipp3.tests.test_protocols_deepres.TestDeepRes
- protocol_screen_deepConsensus
scipion3 tests xmipp3.tests.test_protocol_screen_deepConsensus.TestXmippProtScreenDeepConsensus

**Comment by albertmena** [comment]
We consents to use tensoflow 2.4 that requires CUDA 11 (hardware from 2013)
https://stackoverflow.com/questions/50622525/which-tensorflow-and-cuda-version-combinations-are-compatible    
https://www.tensorflow.org/install/source?hl=es-419#gpu
https://gist.github.com/standaloneSA/99788f30466516dbcc00338b36ad5acf

**Comment by albertmena** [comment]
https://github.com/I2PC/xmipp/pull/761 creates a new environment!
