### ISSUE TITLE
Defocus group protocol fails

### ISSUE THREAD

**Issue by oierlauzi** [I2PC/scipion-em-xmipp#650]
I have tested the defocus group with several datasets (all with a CTF assigned to them) and it always fails with the following error:

```
00001:   Traceback (most recent call last):
00002:     File "/home/olauzirika/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 201, in run
00003:       self._run()
00004:     File "/home/olauzirika/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 252, in _run
00005:       resultFiles = self._runFunc()
00006:     File "/home/olauzirika/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 248, in _runFunc
00007:       return self._func(*self._args)
00008:     File "/home/olauzirika/xmipp-bundle/src/scipion-em-xmipp/xmipp3/protocols/protocol_ctf_defocus_group.py", line 140, in createOutputStep
00009:       df.setDefocusMin(minDef)
00010:   AttributeError: 'DefocusGroup' object has no attribute 'setDefocusMin'
00011:   Protocol failed: 'DefocusGroup' object has no attribute 'setDefocusMin'
```

**Comment by oierlauzi** [comment]
@pconesa @JorMaister @fonsecareyna82  the issue appears because setXXX methods were deleted from DefocusGroup. Is there any possibility of re-adding them to Scipion? If not, we are thinking about setting the corresponding private attributes of the class to fix this issue.

**Comment by pconesa** [comment]
I think the model is designed to update min and max values when adding a ctf through addCTF

Now, if there is a case where this is not possible. Then I think it does not harm to add a setter for both, min and max and sum

Another option to go through the same addCTF would be to create a "Fake CTF" and use addCTF model.

TBH, I've never seen this as an output. Actually, I wasn¡t aware of its existence.

**Comment by albertmena** [comment]
One option is to deprecate the protocol; @cossorzano what is your opinion?
