### ISSUE TITLE
Screen particles protocol, reject by Variance no threshold

### ISSUE THREAD

**Issue by rsanchezgarc** [I2PC/scipion-em-xmipp#72]
The protocol allows for automatic rejection on Z-score threshold, by automatic rejection on Variance does not allow to provide a threshold

**Comment by dmaluenda** [comment]
It was thought in a different way. The thing is, the Z-score is well-normalized and you can estimate a threshold before running the protocol (usually around 3). However, the variance score is not standarized and the can return different ranges (usually between 0 and 1, but not necessary).

Then, the protocol includes an automatic thresholding based on the histogram, but not an user defined threshold. If you still want to cut at certain value, the easy way is to open the 'Analyze Results', sort by that column and select to/from a certain particle and, finally, create a subSet. In this way, you could explore the trend of the variance score to take a good decision.
