### ISSUE TITLE
Not able to install Xmipp 

### ISSUE THREAD

**Issue by aplearnercc** [I2PC/scipion-em-xmipp#748]
![error_commandprompt](https://github.com/I2PC/scipion-em-xmipp/assets/142571864/15fcf47e-d8fc-4101-841e-8bd0284edc04)
![xmipp_config](https://github.com/I2PC/scipion-em-xmipp/assets/142571864/f7ecf638-371c-4ad9-8ca2-30f6601916b9)
Hi All,

I am trying to install Scipion and Xmipp in our cluster environment but facing issue from few weeks. Although Scipion is getting installed successfully but Xmipp is failing with error failed to install googletest dependence but in compile log error says compiler greater than equal to c++14 is required . I need help as this software is very important for us.

1: I am doing it in conda environment.
2. Scipion getting installed but Xmipp failing
3. OS: centos 7.9.2
4. conda version:23.5.2
5.  compile logs attached for reference
6. Scipion version I am trying to install:3.0.0
7. gcc version :10.4.0
8. cuda:11.0.3
9. oepnmpi:4.1.0
10. xmipp config file and error screenshot attached for reference
[compileLOG.txt](https://github.com/I2PC/scipion-em-xmipp/files/13446867/compileLOG.txt)

**Comment by albertmena** [comment]
Hi @aplearnercc and sorry for the long waitting.
As you going to install xmipp to be used inside Scipion the best way to install it is running:
```
scipion3 run ./xmipp
scipion3 installp -p path/to/scipion-em-xmipp
```

Are you sure the default gcc version of your system is 10.4.0? you can run` gcc --version` and `g++ --version`

**Comment by albertmena** [comment]
More details about the issue here:
https://github.com/I2PC/xmipp/issues/817
