### ISSUE TITLE
scipion plugin update to 3.23.11 fails 

### ISSUE THREAD

**Issue by chewyalvin** [I2PC/scipion-em-xmipp#772]
Following error message instruction was followed:
>>> WARNING: Image library not found!
  > Please install Xmipp to get full functionality. 

error log message in the plugin manager:
00001:   Some error occurred when importing xmipp_base (from Xmipp binding): libhdf5_serial.so.103: cannot open shared object file: No such file or directory
how to resolve this?

(Configuration->Plugins->scipion-em-xmipp -> expand, in Scipion plugin manager window)
![1](https://github.com/I2PC/scipion-em-xmipp/assets/26482094/05d5b0f7-89ed-4b6d-8dd3-b2c97ddddd1e)
![Error-log_2024-02-07 13-39-26](https://github.com/I2PC/scipion-em-xmipp/assets/26482094/041ae22c-ae13-426d-9f2e-aca9a29f4dac)

**Comment by chewyalvin** [comment]
[reportInstallation.tar.gz](https://github.com/I2PC/scipion-em-xmipp/files/14189656/reportInstallation.tar.gz)
adding on the installation error file upon running the following cmd: 
scipion3 installb xmippSrc -j 8

**Comment by albertmena** [comment]
Hello @chewyalvin and sorry for the long wait.
Looks like you dont have cmake installed, please install it
https://i2pc.github.io/docs/Installation/Requirements/index.html#cmake
