### ISSUE TITLE
Add acquisition info to create gallery protocol

### ISSUE THREAD

**Issue by fede-pe** [I2PC/scipion-em-xmipp#783]
Create gallery protocol does no set acquisition info. This breaks posterior compatibility with some programs.

![image](https://github.com/I2PC/scipion-em-xmipp/assets/49978869/247e0310-fce0-4baf-918c-0461bb324145)

**Comment by oierlauzi** [comment]
Relion protocols require a CTF assignation, even if not used. Please use "simulate CTF" protocol to add a CTF and acquisition.

**Comment by fede-pe** [comment]
Thanks!
