### ISSUE TITLE
Possible bug deepConsensus validate Deep learning toolkit

### ISSUE THREAD

**Issue by rsanchezgarc** [I2PC/scipion-em-xmipp#80]
According to @cossorzano , validation error in deepLearningToolkit is triggered in protocol_screen_deepConsensus.py 

errorMsg = validateDLtoolkit(errorMsg, model="deepConsensus4",
assertModel=self.addTrainingData.get()==self.ADD_DATA_TRAIN_PRECOMP)

It is probably because deepConsensus4 is misspelled

**Comment by dmaluenda** [comment]
Ouch! My fault!! That's totally a misspelled ;-p

**Comment by dmaluenda** [comment]
Fixed in #77
