### ISSUE TITLE
Typo error

### ISSUE THREAD

**Issue by rsanchezgarc** [I2PC/scipion-em-xmipp#95]
DeepLearnigToolkit should be spelled DeepLearningToolkit in at least two points:

https://github.com/I2PC/scipion-em-xmipp/blob/406d80b9f98f3a98d6347895aa31fc7f413d068c/xmipp3/__init__.py#L111

and

https://github.com/I2PC/xmipp/blob/5e5551c49b5f9d0825e5dce565a1fd1977828d7a/applications/scripts/deep_consensus/deep_consensus.py#L34

**Comment by dmaluenda** [comment]
Thanks @rsanchezgarc !

Fixed in 98028857840c8f627cb47250bfe3ac096a1bb645 and [e86f271](https://github.com/I2PC/xmipp/commit/66478282975fc34bc0a0f4733c57efd36e86f271).
